### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by luisdavim** [helmwave/docs#33]
Hi, just wanted to point out that `hlemsman` does support parallelisation, you can configure a max number of parallel releases, I think the default is 10 and releases with the same priority will be released in parallel.
Can you update your comparison doc?

Thanks.

**Comment by zhilyaev** [comment]
Thank you for your update. 
Nowadays we do not have free time to follow the changelogs of other decisions.

**Comment by zhilyaev** [comment]
Can @luisdavim  create PR? That would be great!

**Comment by luisdavim** [comment]
> Thank you for your update. 
> Nowadays we do not have free time to follow the changelogs of other decisions.

It has had this feature for many years, I believe believe this project existed. 

I can open a PR.

**Comment by r3nic1e** [comment]
We've updated the docs on that
